name: Auto Create PR to Main

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const { repo, owner } = context.repo;
              const result = await github.rest.pulls.create({
                owner,
                repo,
                title: 'Merge changes from dev to main',
                head: 'dev',
                base: 'main',
                body: 'Automated pull request created after push to dev branch'
              });
              console.log('PR Created:', result.data.html_url);
            } catch (error) {
              console.error('Error creating PR:', error);
              throw error;
            }
